-- Example:
--   require("atlas").setup({
--     providers = {
--       ---@type AtlasGitLabConfig
--       gitlab = {
--         base_url = "https://gitlab.com",
--         token    = vim.env.GITLAB_TOKEN,
--         cache_ttl = 300,
--       },
--     },
--     issues = {
--       ---@type AtlasGitLabIssuesConfig
--       gitlab = {
--         views = {
--           { name = "Assigned", key = "1", scope = "assigned_to_me", state = "opened" },
--           { name = "Created",  key = "2", scope = "created_by_me",  state = "opened" },
--           { name = "All open", key = "3", scope = "all",            state = "opened" },
--         },
--       },
--     },
--   })
--
-- View options map directly to GitLab API:
--   scope:    "created_by_me" | "assigned_to_me" | "all"
--   state:    "opened" | "closed" | "all"
--   labels, milestone, assignee_username, author_username, search
--   order_by: "created_at" | "updated_at" | "priority" | ...
--   sort:     "asc" | "desc"
--
-- Anything not covered above can be passed via `extra_params = { key = "value", ... }`.

---@class AtlasGitLabIssuesSearchConfig
---@field scope "created_by_me"|"assigned_to_me"|"all"|nil
---@field project string|number|nil
---@field state "opened"|"closed"|"all"|nil
---@field labels string|nil
---@field milestone string|nil
---@field assignee_username string|nil
---@field author_username string|nil
---@field search string|nil
---@field sort "asc"|"desc"|nil
---@field order_by "created_at"|"updated_at"|"priority"|"due_date"|"label_priority"|"milestone_due"|"popularity"|"weight"|"title"|nil
---@field extra_params table<string, string>|nil

---@class AtlasGitLabIssuesViewConfig : IssuesViewConfig, AtlasGitLabIssuesSearchConfig
---@field current_repo boolean|nil

---@class AtlasGitLabIssuesConfig
---@field views AtlasGitLabIssuesViewConfig[]|nil
